# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Categoria',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
